name: Alex Recommends

on: pull_request

jobs:
  alex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run Alex Recommends he is ugly
      uses: brown-ccv/gh-actions/alex-recommends@alex
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pr_only: false
        glob_pattern: "services/*"
