name: prod-deploy-on-merge
on:
  push:
    branches:
      - main
jobs:
  dispatch_prod_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          repository: brown-ccv/ccv-website-nuxt
          submodules: recursive
      - name: Install
        run: npm ci 
      - name: Generate Static Content
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          git submodule set-branch -b main content
          git submodule update --remote
          npm run generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CCV_BROWN_EDU }}'
          firebaseToolsVersion: 9.12.1 # Pin firebase tools versions to same as ccv-website-nuxt
          projectId: ccv-brown-edu
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
